### ISSUE TITLE
LG Controller access (48CX)

### ISSUE THREAD

**Issue by sneidaa** [Maassoft/ColorControl#2] opened 2020-08-30 13:54 UTC
I have a LG CX 48 running on the same network as the ColorControl (v1.1.0.0) running on a windows 10 machine. Setting display modes works, unfortunately the "LG controller" does not: "It seems there's no LG TV available! Please make sure it's connected to the same network as this PC."

Are there any specific settings needed on the TV? CX not supported? Region dependent (its a EU model)?

**Comment by Maassoft** [comment] 2020-08-30 14:31
Could you please look in the Windows Device Manager if you see your TV there?
The app looks in the Device Manager if there's a LG TV available with "[LG]" in the name:

![image](https://user-images.githubusercontent.com/70057942/91661684-e3dffa00-eadd-11ea-935c-25db65b99ef4.png)

**Comment by sneidaa** [comment] 2020-08-30 14:42
no, there is none in the device manager. how to get it there?:)

the lg cx is connected to the pc via hdmi and in the same network as the pc.

**Comment by Maassoft** [comment] 2020-08-30 15:12
It could be that UPnP is disabled and that Windows is not discovering any network devices.
Here's a link on how to enable that: https://www.computerhope.com/issues/ch001367.htm
But I'm not 100% sure this the issue. It could be also firewall settings or Windows services that are not running.

**Comment by laxu** [comment] 2020-09-06 10:40
CX definitely works. Only time I have seen the app not find the interface is when the app was set to start on logon but I think that issue has already been fixed.

I have both my computer and the LG CX connected via WiFi.

**Comment by netjack7** [comment] 2020-11-05 13:54
I'm able to get it to power off when computer powers off but when I turn the computer on the screen doesn't power on. Also, when I run the "test power off/on," it powers off fine but when I try to hit enter to power on, nothing. I get this error
![11-5-2020 8-51-28 AM](https://user-images.githubusercontent.com/74004316/98249345-22fa5380-1f44-11eb-9326-fdc6bab5025f.png). 

I have no digital media devices in Device Mgr. 

I also have a bunch of errors in the log: 
![11-5-2020 8-53-03 AM](https://user-images.githubusercontent.com/74004316/98249549-5c32c380-1f44-11eb-8685-c7e811a25094.png). 

LG controller looks ok: 
![11-5-2020 8-53-30 AM](https://user-images.githubusercontent.com/74004316/98249581-69e84900-1f44-11eb-8f19-60e482926e12.png)

**Comment by netjack7** [comment] 2020-11-05 14:01
> 
> 
> CX definitely works. Only time I have seen the app not find the interface is when the app was set to start on logon but I think that issue has already been fixed.
> 
> I have both my computer and the LG CX connected via WiFi.

Do you have the CX show up under digital media device in device manager?

**Comment by Maassoft** [comment] 2020-11-05 18:48
> I'm able to get it to power off when computer powers off but when I turn the computer on the screen doesn't power on. Also, when I run the "test power off/on," it powers off fine but when I try to hit enter to power on, nothing. I get this error
> ![11-5-2020 8-51-28 AM](https://user-images.githubusercontent.com/74004316/98249345-22fa5380-1f44-11eb-9326-fdc6bab5025f.png).

Maybe there's something wrong with wpcap.dll on your system? Look at this link: [https://stackoverflow.com/questions/58010149/unable-to-load-dll-wpcap-dll-the-specified-module-is-not-found](url)
I have a wpcap.dll in my C;\Windows\System32 directory, but I don't know exactly how it got there, haha. A regsvr32 of this dll might fix your problem, but I'm not sure.

> 
> I have no digital media devices in Device Mgr.
> 

If you see the device in the app it probably found in under "Software devices" in device manager.

**Comment by netjack7** [comment] 2020-11-05 19:39
Bingo on the software devices. I was googling wpcap and it appears it belongs to an old program - https://www.winpcap.org/install/. Is that where you originally got it? Your link doesn't work.

**Comment by Maassoft** [comment] 2020-11-05 22:50
Yes, maybe I installed it from there, but it probably was already on my system before I even started working on this app.

**Comment by netjack7** [comment] 2020-11-05 23:51
I installed it but still not getting it to turn on when I power on the machine. Now during the testing, there is some progress - it turns off, when I try to hit enter to turn on, it takes 3 enters to get it to wake. However, still nothing on boot up. 

Here's the debug code:
2020-11-05 18:49:36.7269|DEBUG|ColorControl.WOL|Waking device with MAC-address EC-6C-9A-8E-2B-92
2020-11-05 18:49:36.7309|DEBUG|ColorControl.WOL|Opening network device: \Device\NPF_{75C1E543-A0EB-445F-ADF8-29335F013CBF}
2020-11-05 18:49:36.7309|DEBUG|ColorControl.WOL|Opening network device: \Device\NPF_{74EFA5FD-F289-44A6-93A8-54AD1047EA9D}
2020-11-05 18:49:36.7309|DEBUG|ColorControl.WOL|Opening network device: \Device\NPF_{E653B900-BF83-44D2-A6D6-1D59B2306BEA}
2020-11-05 18:49:36.7309|DEBUG|ColorControl.WOL|Opening network device: \Device\NPF_{FC5CC9A4-928E-41FF-84F8-D036B4C77425}
2020-11-05 18:49:36.7429|DEBUG|ColorControl.WOL|Opening network device: \Device\NPF_Loopback
2020-11-05 18:49:44.9440|DEBUG|ColorControl.WOL|Waking device with MAC-address EC-6C-9A-8E-2B-92
2020-11-05 18:49:44.9479|DEBUG|ColorControl.WOL|Opening network device: \Device\NPF_{75C1E543-A0EB-445F-ADF8-29335F013CBF}
2020-11-05 18:49:44.9479|DEBUG|ColorControl.WOL|Opening network device: \Device\NPF_{74EFA5FD-F289-44A6-93A8-54AD1047EA9D}
2020-11-05 18:49:44.9479|DEBUG|ColorControl.WOL|Opening network device: \Device\NPF_{E653B900-BF83-44D2-A6D6-1D59B2306BEA}
2020-11-05 18:49:44.9479|DEBUG|ColorControl.WOL|Opening network device: \Device\NPF_{FC5CC9A4-928E-41FF-84F8-D036B4C77425}
2020-11-05 18:49:44.9479|DEBUG|ColorControl.WOL|Opening network device: \Device\NPF_Loopback

**Comment by Maassoft** [comment] 2020-11-06 11:14
I can see it's trying to send the WOL-packet to 5 networks on your system. Problem is that for the waking up via WOL to work, the tv has to be in standby mode and the Turn On via Wi-Fi has to be enabled. If the tv is just powered off or running the short image retention cleanup process, it's not really in standby mode and won't respond to WOL-packets (it will respond to a real power on, though). If you hear the relay clicking after power off, it should be in standby mode. Problem is that I haven't found a good way to detect if the tv is in standby mode or in semi standby mode so I haven't implemented the normal power on.

**Comment by netjack7** [comment] 2020-11-06 12:09
Well the Wuick Start+ mode is suppose to act like a standy mode. I've tried with it on and off and no luck. Ok so I guess this gives me 50% of what I want which is turns of but not on. I'll take that for now.

**Comment by netjack7** [comment] 2020-11-19 01:26
Damn - reinstalled my OS and now I can't get the program to find the tv. I've got network discovery turned on :(

**Comment by netjack7** [comment] 2020-11-19 11:40
Nvm fixed that issue. Another issue - how do I remove a second LG tv from the device list. I only want to manipulate one but 2 are found under devices.

**Comment by Maassoft** [comment] 2020-11-19 16:21
I'm afraid that isn't possible at this time. Only way to get rid of the unwanted device is to remove it from device manager (under Digital Media Devices and Software devices). Maybe I will let it remember the preferred tv in a new version. Is your preferred tv not the first in de drop down?

**Comment by netjack7** [comment] 2020-11-19 16:25
No and it's not even listed in my Digital media devices

**Comment by Maassoft** [comment] 2020-11-19 16:37
I think it may be a disabled device, does device manager show it if you go to View->Show hidden devices? I used to filter out the disabled devices, but if I need to wake the tv it is disabled and I still need it.

**Comment by netjack7** [comment] 2020-11-19 16:41
Shit you're right. It's a disabled device.

**Comment by netjack7** [comment] 2020-11-21 22:54
I have 4 oleds and the one I want to control is the last one. Even when I
disable the wifi on a TV, it still shows up.
[image: image.png]

[image: image.png]

**Comment by netjack7** [comment] 2020-11-21 22:58
Ahh - I figured out how to remove it from software devices.

**Comment by Maassoft** [comment] 2020-11-22 08:53
I just published a new release. This version will now remember which tv was selected. On startup it will automatically select that one instead of always the first one.

**Comment by netjack7** [comment] 2020-11-22 11:25
Strangely enough, when I click on the exe, it doesn't start and nothing
happens (there's no icon in the taskbar). Have you tested it?

**Comment by Maassoft** [comment] 2020-11-22 13:32
Strange, yes I've tested it and it currently works on my machine with no problems.
What happens if you remove the files in your profile folder:

C:\Users\<username>\AppData\Roaming\Maassoft\ColorControl

Maybe back them up somewhere so you don't lose you're settings.
Will it startup correctly then?

**Comment by netjack7** [comment] 2020-11-22 13:44
Nothing. Deleted all of them, click on colorcontrol.exe and nothing happens
(and no new files written in the Color Control App Data folder.

**Comment by netjack7** [comment] 2020-11-22 13:45
Why do you not use an installer.exe?

**Comment by Maassoft** [comment] 2020-11-22 14:55
I created a new version. Probably doesn't fix your bug, but should show an error dialog if something goes wrong during initialization.
I used an installer before, but others wanted a more portable version. I guess I can't please everyone 😅

**Comment by netjack7** [comment] 2020-11-22 15:01
I can appreciate that!

So I downloaded the new version and same thing. I click - absolutely
nothing happens (no mouse movement, nothing in task bar, no new folder in
Roaming).

**Comment by netjack7** [comment] 2020-11-22 15:05
Reinstalled 1.2 and that works no problem.

**Comment by Maassoft** [comment] 2020-11-22 16:41
I created a new version: 1.3.2.0.
Could it be that you don't have a Nvidia GPU? I tested it on a system with only Intel integrated graphics and the application crashed after a few seconds. Should be fixed in this version now.

**Comment by netjack7** [comment] 2020-11-22 16:44
I have a 3080 :) I'll test it.

**Comment by netjack7** [comment] 2020-11-22 17:02
Still nothing....

**Comment by Maassoft** [comment] 2020-11-22 18:46
Weird, I don't know what else I can do.
Maybe there's a message in the Event Viewer? Have you looked there?

**Comment by netjack7** [comment] 2020-11-22 18:49
What exactly did you update in the new version? Just the ability to select
a specific lg tv?

**Comment by Maassoft** [comment] 2020-11-22 20:38
I added more changes in the new version and it's probably the support for AMD cards that caused it. I've created a new release which has the AMD code disabled, so it should not cause a crash anymore.

**Comment by netjack7** [comment] 2020-11-22 20:55
Nothing. Tell me what exactly to do in event viewer so I can share w/ you.
I can do a zoom mtg w/ you when you have time to show you what isn't
happening.

**Comment by Maassoft** [comment] 2020-11-22 21:06
Check in event viewer under Windows Logs\Application if there's a message at the time you start the application.
I can't do a Zoom meeting now, it's 10pm here and I call it a day. I suggest that you keep using version 1.2 for the time being.

**Comment by netjack7** [comment] 2020-11-22 21:51
Ok, I will do that.

**Comment by Maassoft** [comment] 2020-11-29 22:22
Can you test if the problem is resolved with release 1.3.5.0? There was a bug with scaling, do you use a different value than 100% in Windows?

**Comment by netjack7** [comment] 2020-11-29 22:44
Yes it's working and yes I'm using 115% scaling.

**Comment by netjack7** [comment] 2020-11-30 11:58
Now how do you remove devices from the drop down?

**Comment by Maassoft** [comment] 2020-11-30 16:10
You can't, but the app will now remember the selected tv. So you only have to select the desired tv from the drop down and the next time the app starts it will automatically select that one as the default one (instead of the first item in the list).

**Comment by netjack7** [comment] 2020-11-30 21:03
BTW - good news w/ this version program at least starts. Bad news is, it
doesn't remember the device selected on reboot. I wonder if it's because
I'm in a rare position in having 3 LG oleds.

**Comment by Maassoft** [comment] 2020-11-30 22:02
Haha, well, I have 2 LG oleds, a C8 and a C9, but fortunately the C9 which is connected to the pc is the first one in the drop down.
Could you check in the setting "PreferredMacAddress" is written to the LgConfig.json file in your AppData\Roaming\Maassoft\ColorControl folder?
The address should correspond with the tv you selected in the drop down. You can check the address in device manager:
![image](https://user-images.githubusercontent.com/70057942/100670908-ddbd1c00-335f-11eb-8d65-faa5266a96f7.png)

**Comment by netjack7** [comment] 2020-12-01 12:07
And what boggles my mind is how the program picks up the other tvs even
though I have their wireless turned off! How is it doing that?

**Comment by netjack7** [comment] 2020-12-01 12:08
And what is this error:
2020-12-01 07:06:38.4608|DEBUG|ColorControl.LgService|Cannot apply
LG-preset: no connection could be made
2020-12-01 07:06:38.4827|DEBUG|ColorControl.LgService|Cannot refresh apps:
no connection could be made

Could not refresh app.

**Comment by netjack7** [comment] 2020-12-01 12:39
So progress - I was able to manually change the mac address in the json
file to match the correct LG so now it remembers. However, now when I
startup, under LG controller tab, the option to auto power on/off doesn't
seem to stick (meaning I have to click check marks every time).

**Comment by Maassoft** [comment] 2020-12-01 18:04
> And what boggles my mind is how the program picks up the other tvs even though I have their wireless turned off! How is it doing that?

It just uses device manager for that. Windows remembers all devices that were active once, but could be disconnected currently,

> And what is this error: 2020-12-01 07:06:38.4608|DEBUG|ColorControl.LgService|Cannot apply LG-preset: no connection could be made 2020-12-01 07:06:38.4827|DEBUG|ColorControl.LgService|Cannot refresh apps: no connection could be made Could not refresh app.

I think it tried to connect to a disconnected tv. Problem is whenever you switch to another tv in the drop down, it will automatically want to connect to it. I admit having more than 1 device is a bit problematic for the app at this time.

> So progress - I was able to manually change the mac address in the json file to match the correct LG so now it remembers. However, now when I startup, under LG controller tab, the option to auto power on/off doesn't seem to stick (meaning I have to click check marks every time).

That's strange, these check marks are saved to the same file where you changed to mac address. "PowerOnAfterStartup" should be set to true after you checked the right check box and closed the app (only then it will save to file).

**Comment by Maassoft** [comment] 2020-12-04 13:00
I created a new release which enables you to change the device search filter. If you set it to "CX", then only your CX should appear in the drop down.

**Comment by Maassoft** [comment] 2021-02-23 15:31
I'm closing this issue now because of multiple reports of users who are successfully using the app with CX's.

**Closed by Maassoft** 2021-02-23 15:31 UTC
