### ISSUE TITLE
Error when Generating new HDR Color Profile

### ISSUE THREAD

**Issue by Jason-GitH** [Maassoft/ColorControl#306] opened 2023-12-29 04:17 UTC
I changed the minTML and minCLL to 0 nits and maxTML and maxCLL to 800 nits and left other settings at default. When I clicked Generate, I get the following error:

![image](https://github.com/Maassoft/ColorControl/assets/101422827/3d8fe72c-477e-47b8-b250-ba9623967cb7)

**Comment by Maassoft** [comment] 2023-12-29 13:29
Duplicate of #305, is fixed with v9.8.0.1.

**Closed** 2024-01-15 18:45 UTC
