### ISSUE TITLE
Missing Presets Menu.

### ISSUE THREAD

**Issue by PsYchitOut** [Maassoft/ColorControl#62] opened 2021-12-24 02:41 UTC
For some reason the presets presets submenu in the LG control Menu is missing. It has actually always been gone but I never knew to look for it. the program doesn't look like its scaling right especially when I shrink the window further, possibly that might be causing it.. My PC is at 3840x2160 300% scale but the issue persists regardless of what scale I am on. I can see different pre set options in the task bar menu under "LG presets" and they do kinda work. I think its trying to put in macros for the wrong model TV so any of the complex ones just dead end. I tried older versions as well as deleting the data out of the appdata folder. Neither steps changed anything.
![Screenshot 2021-12-23 203009](https://user-images.githubusercontent.com/24470080/147308699-aa156b76-cf4e-488a-b2d1-1d83586b7320.png)
![Screenshot 2021-12-23 203210](https://user-images.githubusercontent.com/24470080/147308700-2ebba140-3f64-48c7-9521-cdd67826ccd1.png)

**Comment by Amoeba00** [comment] 2021-12-24 03:20
What video card and what are your scaling settings in the NVCP?
Also, is your HDMI input set to PC mode or regular HDMI?

**Comment by PsYchitOut** [comment] 2021-12-24 04:21
Thanks for getting back so quick.

My Video Card a ASUS brand RTX-3080. I
believe it's part of their TUF gaming series. That's what the numbers on
the card and in CPUz show. It's part of a pre build with a custom water
block so I don't know 100%

My HDMI input is set to PC. My display scaling in NVCP is set to integer
scaling and I deleted 4096x2160 resolution option in CRU as outline in the
Reddit OLED settings guide to fix some scaling issues. The same guide that
I found you in actually.
https://www.reddit.com/r/OLED_Gaming/comments/mbpiwy/lg_oled_gamingpc_monitor_recommended_settings/

I also have a seperate HDMI cable going to my motherboards IGP port. I have
that outputting basically a dummy 800x600 60HZ video signal so I can have a
direct line to my home theater system. HTS is a LGSP9YA. (If only you could
find a way to remote control that.)

Just to make sure I tried disabling the second display to see if that would
fix it. It actually almost seemed like it was going to work for a second. I
could see the menu. Sept nothing would scale up to a point I could read it
and when I restarted the pc it went back to how it was. Couldn't even
reproduce the glitch.

**Comment by Amoeba00** [comment] 2021-12-25 21:46
So wait - you can't reproduce the glitch and you have two separate connections from the same computer?  
What happens if you have a single HDMI connection from your video card to the LG and nothing else?
Also, make sure in Windows you have the onboard IGP disabled as a monitor/display device.
Sometimes, starting from scratch can help isolate the issue.

Single video connection to single display.  Everything else disabled.
Make sure you have the latest/clean install of the drivers.
Reboot.
Make sure everything else works like it should with no glitches.
THEN - add this software connection and see what happens.

**Comment by PsYchitOut** [comment] 2021-12-26 00:52
When I said I couldn't reproduce the glitch I meant the glitch that fixed
the issue lol. For one moment in a combination of resetting displays
changing resolutions and clearing the appdata it fixed itself. Then when I
closed and reopened the app it was broken again.

 It seems the issue is the program doesn't scale up to 300% properly. Which
is understandable most people don't use their living room home theater as
their home office. Quite a few programs have that problem and I've gotten
quite used to having to drop it down when I need to.

 However for some reason it's getting stuck trying to scale up and I can't
seem to break it out of that. Just to make absolutely sure I wasn't wasting
your time I unplugged the second HDMI line before I turned on the PC,
Dropped the scaling down to 100%, deleted the folder from appdata/roaming
deleted the folder I had extracted and even for good measure download the
next oldest version and when I started it up it was still messed up. I
tried dropping the resolution down to 1080p and just got a what looks like
the corner of the Nvidia profile window blown up to astronomical degrees. I
even tried running through the IGP just for good measure and it's the same
thing.

 Is there another file this thing saved on my PC that I'm missing? What is
telling it to scale up so high?

**Comment by PsYchitOut** [comment] 2021-12-26 01:50
Sorry about that I just noticed your suggestion about getting clean
drivers. I just ran a ddu and replaced my Nvidia drivers with fresh ones.
Set the scaling to 100% then start the program it fixes it. Course it
messes up if you restart the computer when your back on 300% scaling.

Also in the small period where I was able to access it I tried writing a
chain of commands it kept missing ones in the chain. But one thing at a
time lol.

**Comment by Maassoft** [comment] 2021-12-27 13:46
I've just released version 5.0.0.0 where the default scaling method has been changed to "DPI Unaware GDI Scaled". Can you test if this fixes the problem?

**Comment by PsYchitOut** [comment] 2021-12-27 15:17
Not until about 5:00 p.m. central when I get out of work. But I'll make it
the first thing I do. Thanks in advance for getting on top of it so quickly.

**Comment by Amoeba00** [comment] 2021-12-27 15:33
>But one thing at a time lol.
Exactly! - Looks like you are headed in the right direction though and hopefully this new version fixes it.

**Comment by Maassoft** [comment] 2022-01-24 18:13
Should be fixed with 5.0.0.0.

**Closed by Maassoft** 2022-01-24 18:13 UTC
