### ISSUE TITLE
Display Frequency does not correctly change from 23.976Hz to 24Hz

### ISSUE THREAD

**Issue by mdannp** [Maassoft/ColorControl#126] opened 2022-09-13 22:50 UTC
I have 3 settings with included 23Hz 24Hz and 60Hz (the 23Hz setting actually uses 23.976Hz as desired).

Following transitions work fine:
60Hz -> 24Hz
60Hz -> 23.976Hz
24Hz -> 23.976Hz
24Hz -> 60Hz
23.979Hz -> 60Hz

but the transition from 23.976Hz to 24Hz does not work and the display remains at 23.976Hz, while ColorControl shows 24Hz in the active refresh rate. All other settings from the 24Hz profile are taken in this case though.
There are no error message in the log for any of those transitions

**Comment by Maassoft** [comment] 2022-09-15 21:22
I think this might be caused by the function EnumDisplaySettings I'm using to enumerate the modes and with it refresh rates are reported in whole numbers. 23.979Hz might be reported as 23Hz (as you noticed) and due to casting/rounding 24Hz is chosen in some cases.
I'll have a look and it probably will be fixed in the next release.

**Comment by mdannp** [comment] 2022-09-18 10:51
Thank you very much for the great tool!

As far as I understand, all display tools I saw always round down, so 23.976Hz becomes 23 and 59.94Hz becomes 59.
While 23.976Hz is active, ColorControl actually shows 24Hz. I'd assume that when the new 24Hz FPS rate is selected, it is skipped since ColorControl assumed it is alread 24Hz. If my assumption is correct its just a matter of changing round() to floor()

**Comment by Maassoft** [comment] 2022-10-30 08:30
Should be fixed now with v8.0.0.0.

**Closed** 2022-12-10 18:27 UTC
