### ISSUE TITLE
Unandled Exception with 5.5.1.0

### ISSUE THREAD

**Issue by gorman42** [Maassoft/ColorControl#80] opened 2022-02-27 17:15 UTC
When I launch the program, I get this:

![image](https://user-images.githubusercontent.com/38404727/155892390-8ffe0cb8-a812-4a2f-a1a9-ceac24753182.png)

**Comment by gorman42** [comment] 2022-02-27 17:32
Also, since I can't access the program anymore, where the hell is the "start with system start" setting saved. I've deleted all instances of colorcontrol.exe from the registry and still receive an error message that Windows cannot find it, at startup.

**Comment by Maassoft** [comment] 2022-02-27 18:18
I think this might be caused by a corrupt Settings.json file.
Can you check in the C:\Users\username\AppData\Roaming\Maassoft\ColorControl folder if the file contents are there or maybe corrupted? You can delete it and then it will be regenerated again.

**Comment by gorman42** [comment] 2022-02-27 18:24
I will check later and report back. I'm now kicking myself in the ass for not thinking about the Maassoft name in the roaming folder. I looked for ColorControl and did not find it, obviously.

**Comment by gorman42** [comment] 2022-02-28 00:50
Yup, that was it. I had to delete LgConfig.json too, as accessing the LG tab was giving me a similar error. Both files were full of Null characters.

Thanks for pointing me in the right direction.

**Comment by Maassoft** [comment] 2022-02-28 22:29
No problem. Did you by any chance had a crash (blue screen) or spontaneous restart of your system? I've had some corrupted files as well and it always seems to happen after a system crash. I think write caching of SSD's could be the culprit. The SSD does not directly write the data, but after a delay. If your system crashes in the mean time the data is lost.

**Comment by Maassoft** [comment] 2022-04-07 17:35
Should be fixed with 5.7.0.0.

**Closed by Maassoft** 2022-04-07 17:35 UTC
