### ISSUE TITLE
HDR toggle through commandline opens settings window

### ISSUE THREAD

**Issue by gorman42** [Maassoft/ColorControl#39] opened 2021-08-09 17:18 UTC
I have tried to create automation for HDR toggle. Only HDR active, using HDR Toggle on a preset. When invoking that preset through command line, it opens Windows video settings window. If using it through the Apply button in your program, this does not happen.

**Comment by gorman42** [comment] 2021-08-09 17:23
I use this command: --nvpreset HDR --nogui

Where HDR is the name of the preset. The first time I use it the Windows HDR setting gets toggled on, with the settings window in the foreground. If I close the window and launch again the command, the Windows settings window appears again and Night light gets toggled on.

It's strange because from within the program everything works fine.

**Comment by gorman42** [comment] 2021-08-09 21:57
If I assign a key shortcut and leave ColorControl in the background everything works fine. Problem is just from the commandline.

Functionally I am set, with a combination of EventGhost and the program running in the background. But I still think it's worth investigating. Thanks for your program, by the way. Much appreciated and useful.

**Comment by Maassoft** [comment] 2021-08-10 09:14
First off, thanks for the compliments!
Now on to your issue. There are some limitations in changing the HDR setting of Windows.
Currently I can change the HDR setting through the Nvidia or AMD API, but whenever I do that the program must stay active, otherwise it will revert back to SDR upon closing ColorControl.
So if you use the command line option and choose to close the program after applying the preset, the only way* to change the HDR setting is through the Display settings app. And this will also happen if you want to disable HDR but didn't enable it through ColorControl.
Changing HDR through the Display app is tricky because I have to use TAB to go to the HDR knob and finally use SPACE to switch it. Can you check how many times you have to press TAB after opening the Display settings app to highlight the HDR button? On my system (Windows 21H1) I need 2 TABs and the app looks like this:

![image](https://user-images.githubusercontent.com/70057942/128840994-1d850a37-aaa1-46a3-97f7-178198c6eccb.png)

\* There are some other possibilities, but I need to investigate that first. And maybe Windows 11 will improve it as well...

**Comment by gorman42** [comment] 2021-08-11 12:14
Hi! I discovered that the settings open even if I have the program minimised in the tray.
Is that expected behaviour too?

Further details in a couple of minutes, from the HTPC I’m using it on.

**Comment by gorman42** [comment] 2021-08-11 12:54
Ok, I've found a way to reproduce it.

First off some details on the system I'm testing it on.
Windows 10 Pro x64 (21H1 build 19043.1083), Ryzen 3 1200, 16GB RAM, RTX 3070 (driver 471.11).

So, from desktop or regular browser (Firefox or Chrome) open I can toggle HDR to my heart's content, without the display settings ever appearing.

Firefox fullscreen (F11) does not create problems, Chrome fullscreen (F11) appears to be fine too.

If I launch Chrome with these parameters through command line:

--kiosk --user-agent="Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36 WebAppManager" https://www.youtube.com/tv#/browse-sets?c=FEwhat_to_watch

I can enter HDR mode ok but, if I toogle it back to HDR off, the Windows display settings appear.

I need to launch it with those parameters to access the old YouTube TV interface for HTPC use. If I omit "--kiosk" and go fullscreen with F11, the problem manifests itself too. Which leads me to believe the problem might be the --user-agent parameter.

But this is where things get confusing. I can't find what exactly triggers it. By testing sometimes it appears to be the user agent, sometimes the --kiosk parameter...

I have tried pretty much all combinations but I'm not managing to come to the bottom of it.

**Comment by Maassoft** [comment] 2021-08-12 10:04
Yes, it happens when HDR is enabled through another app (not by ColorControl) and if ColorControl needs to disable HDR again, it is not working while using the Nvidia API. So in that case only the Display settings app is able to disable HDR.
But I have some good news. I have found a way to enable/disable HDR through the Windows API without using the Display settings app or even the Nvidia/AMD API. This feature will be added to the next release of ColorControl.

**Comment by gorman42** [comment] 2021-08-12 11:33
Glad to read the second part of your message! Is there an ETA? Sorry, I had to ask :-D

As far as the first portion is concerned, HDR is always activated through ControlColor in my examples. There's no other way I use.

**Comment by Maassoft** [comment] 2021-08-13 13:26
I've just released version 4.0.0.0. Maybe you can test if the problem is solved now.

**Comment by gorman42** [comment] 2021-08-14 21:31
Away for some vacation. I’ll test as soon as I get back.

**Comment by gorman42** [comment] 2021-08-21 10:13
I confirm it works correctly!

**Comment by Maassoft** [comment] 2021-08-23 18:10
Great that it's working, I'll close this issue.

**Closed by Maassoft** 2021-08-23 18:10 UTC
